using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Threading;
using System.Windows.Forms;
using PowerPoint = Microsoft.Office.Interop.PowerPoint;
using Office = Microsoft.Office.Core;

namespace PowerPointAddIn1
{
    // ── Settings data object ─────────────────────────────────────────────────
    internal class MagnifySettings
    {
        public float MagnificationFactor { get; set; } = 2.0f;
        public Color BorderColor         { get; set; } = Color.Black;
        public float BorderThickness     { get; set; } = 4.0f;
        public float SoftEdgesPoints     { get; set; } = 0f;
    }

    // ── Feature logic ────────────────────────────────────────────────────────
    internal static class MagnifyFeature
    {
        // Export at 2× slide-point dimensions for a sharp crop
        private const int ExportScale = 2;

        // Tag written on every slide generated by this feature
        private const string MagTag = "MagnifySlide";

        internal static MagnifySettings Settings { get; set; } = new MagnifySettings();

        // ─────────────────────────────────────────────────────────────────────
        // ADD MAGNIFY
        //   Reads the current shape selection on the active slide, exports the
        //   slide to a PNG, then creates a new slide after it that shows:
        //     1. The original slide as a full-slide background.
        //     2. Each selected area cropped and scaled up by MagnificationFactor,
        //        centred on the original area position, with a border.
        // ─────────────────────────────────────────────────────────────────────
        internal static void AddMagnify(PowerPoint.Application app)
        {
            if (app?.ActivePresentation == null)
            {
                Warn("Please open a presentation first.", "No Presentation");
                return;
            }

            var win = app.ActiveWindow;
            if (win.Selection == null ||
                win.Selection.Type != PowerPoint.PpSelectionType.ppSelectionShapes)
            {
                Warn(
                    "Please select one or more shapes on the slide that define the\n" +
                    "areas to magnify, then click 'Add Effect'.",
                    "No Shapes Selected");
                return;
            }

            var sr = win.Selection.ShapeRange;
            if (sr.Count < 1) { Warn("No shapes selected.", "No Shapes"); return; }

            var   pres   = app.ActivePresentation;
            var   src    = win.View.Slide as PowerPoint.Slide;
            int   srcIdx = src.SlideIndex;
            float slideW = pres.PageSetup.SlideWidth;
            float slideH = pres.PageSetup.SlideHeight;
            int   expW   = (int)(slideW * ExportScale);
            int   expH   = (int)(slideH * ExportScale);

            // Collect area geometry; rename shapes with MAG_ prefix so they are
            // easy to identify for future re-runs.
            var areas = new List<(string name, float left, float top, float width, float height)>();
            for (int i = 1; i <= sr.Count; i++)
            {
                var sh = sr[i];
                if (!sh.Name.StartsWith("MAG_", StringComparison.OrdinalIgnoreCase))
                    sh.Name = "MAG_" + i + "_" + sh.Name;
                areas.Add((sh.Name, sh.Left, sh.Top, sh.Width, sh.Height));
            }

            // Temporarily hide marker shapes for a clean slide export
            foreach (var a in areas)
            {
                var sh = FindShape(src, a.name);
                if (sh != null) sh.Visible = Office.MsoTriState.msoFalse;
            }

            string tmpDir = Path.GetTempPath();
            string bgFile = Path.Combine(tmpDir, "mag_bg_" + Guid.NewGuid().ToString("N") + ".png");

            try
            {
                src.Export(bgFile, "PNG", expW, expH);
            }
            finally
            {
                // Always restore marker shapes visibility
                foreach (var a in areas)
                {
                    var sh = FindShape(src, a.name);
                    if (sh != null) sh.Visible = Office.MsoTriState.msoTrue;
                }
            }

            var cropFiles = new List<string>();
            try
            {
                // ── New blank slide after source ──────────────────────────────
                var ns = pres.Slides.Add(srcIdx + 1, PowerPoint.PpSlideLayout.ppLayoutBlank);
                ns.Tags.Add(MagTag, "true");

                // Remove any placeholder shapes that sneak in from the layout
                for (int i = ns.Shapes.Count; i >= 1; i--)
                    try { ns.Shapes[i].Delete(); } catch { }

                // ── 1. Full-slide background (original slide image) ───────────
                ns.Shapes.AddPicture(bgFile,
                    Office.MsoTriState.msoFalse,
                    Office.MsoTriState.msoTrue,
                    0f, 0f, slideW, slideH);

                // ── 2. Magnified cut-outs ────────────────────────────────────
                foreach (var a in areas)
                {
                    string cropFile = Path.Combine(tmpDir,
                        "mag_crop_" + Guid.NewGuid().ToString("N") + ".png");
                    cropFiles.Add(cropFile);

                    // Crop bounds in export-image pixel coordinates
                    int cx = Math.Max(0, (int)(a.left  * ExportScale));
                    int cy = Math.Max(0, (int)(a.top   * ExportScale));
                    int cw = Math.Max(1, Math.Min((int)(a.width  * ExportScale), expW - cx));
                    int ch = Math.Max(1, Math.Min((int)(a.height * ExportScale), expH - cy));

                    using (var bmp     = new Bitmap(bgFile))
                    using (var cropped = bmp.Clone(new Rectangle(cx, cy, cw, ch), bmp.PixelFormat))
                        cropped.Save(cropFile, ImageFormat.Png);

                    // Magnified dimensions in slide points
                    float magW = a.width  * Settings.MagnificationFactor;
                    float magH = a.height * Settings.MagnificationFactor;

                    // Clamp size to slide bounds first, then compute centred position
                    magW = Math.Min(magW, slideW);
                    magH = Math.Min(magH, slideH);

                    float areaCX  = a.left + a.width  / 2f;
                    float areaCY  = a.top  + a.height / 2f;
                    float magLeft = Math.Max(0f, Math.Min(areaCX - magW / 2f, slideW - magW));
                    float magTop  = Math.Max(0f, Math.Min(areaCY - magH / 2f, slideH - magH));

                    // Copy the original shape onto the new slide to preserve its exact
                    // geometry (oval, star, freeform, arrow, etc.); then resize it to
                    // the magnified dimensions and fill it with the cropped image.
                    var origShape = FindShape(src, a.name);
                    PowerPoint.Shape magShape;
                    if (origShape != null)
                    {
                        origShape.Copy();
                        var pasted = ns.Shapes.Paste();
                        magShape       = pasted[1];
                        magShape.Left  = magLeft;
                        magShape.Top   = magTop;
                        magShape.Width = magW;
                        magShape.Height = magH;
                    }
                    else
                    {
                        // Fallback: plain rectangle if the original shape is not found
                        magShape = ns.Shapes.AddShape(
                            Office.MsoAutoShapeType.msoShapeRectangle,
                            magLeft, magTop, magW, magH);
                    }

                    // Fill with the magnified crop; the shape outline clips it to its boundary.
                    magShape.Fill.UserPicture(cropFile);
                    magShape.Line.Visible = Office.MsoTriState.msoTrue;
                    magShape.Line.ForeColor.RGB = ColorTranslator.ToOle(Settings.BorderColor);
                    magShape.Line.Weight = Settings.BorderThickness;

                    if (Settings.SoftEdgesPoints > 0)
                        try { magShape.SoftEdge.Radius = Settings.SoftEdgesPoints; } catch { }
                }

                MessageBox.Show(
                    $"Magnify slide created after Slide {srcIdx}.\n" +
                    $"{areas.Count} area(s) magnified at {Settings.MagnificationFactor:F1}\u00d7.\n\n" +
                    "Tip: adjust the magnification factor via 'Settings' and re-run.",
                    "Magnify Created",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error creating magnify effect: " + ex.Message,
                    "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            finally
            {
                foreach (string f in cropFiles) TryDeleteTempFile(f);
                TryDeleteTempFile(bgFile);
            }
        }

        // ─────────────────────────────────────────────────────────────────────
        // SETTINGS  –  opens the MagnifySettingsForm dialog
        // ─────────────────────────────────────────────────────────────────────
        internal static void ShowSettings()
        {
            using (var dlg = new MagnifySettingsForm(Settings))
            {
                if (dlg.ShowDialog() == DialogResult.OK)
                    Settings = dlg.Result;
            }
        }

        // ── Helpers ───────────────────────────────────────────────────────────
        private static PowerPoint.Shape FindShape(PowerPoint.Slide slide, string name)
        {
            for (int i = 1; i <= slide.Shapes.Count; i++)
                if (string.Equals(slide.Shapes[i].Name, name, StringComparison.OrdinalIgnoreCase))
                    return slide.Shapes[i];
            return null;
        }

        private static void Warn(string msg, string title) =>
            MessageBox.Show(msg, title, MessageBoxButtons.OK, MessageBoxIcon.Warning);

        private static void TryDeleteTempFile(string path)
        {
            if (string.IsNullOrEmpty(path)) return;

            for (int attempt = 0; attempt < 3; attempt++)
            {
                try
                {
                    if (!File.Exists(path)) return;
                    File.Delete(path);
                    return;
                }
                catch (IOException)
                {
                    Thread.Sleep(50);
                }
                catch (UnauthorizedAccessException)
                {
                    Thread.Sleep(50);
                }
                catch
                {
                    return;
                }
            }
        }
    }
}
