using System;
using System.Collections.Generic;
using System.Globalization;
using System.Windows.Forms;
using PowerPoint = Microsoft.Office.Interop.PowerPoint;
using Office = Microsoft.Office.Core;

namespace PowerPointAddIn1
{
    /// <summary>
    /// Implements the three-step Morph-zoom feature:
    ///   1. SelectZoom  – stores selected shapes as zoom areas.
    ///   2. ZoomAdd     – inserts one preview zoom slide per area.
    ///   3. Create      – builds the full Original→Zoom→Original sequence with Morph.
    /// </summary>
    internal static class ZoomFeature
    {
        // Tag written on every slide generated by this feature so they can be
        // cleaned up before a re-run without touching the user's own slides.
        private const string ZoomTag = "ZoomMorphSlide";
        private const string ZoomSourceSlideIdTag = "ZoomSourceSlideId";
        private const string ZoomAreaMarkerTag = "ZoomAreaMarker";

        // ppEffectMorphByObject = 3954, ppEffectMorphByWord = 3955, ppEffectMorphByChar = 3956
        // (Microsoft 365 / PowerPoint 2016+ correct values)
        private const int MorphByObject = 3954;
        private const int MorphByWord   = 3955;
        private const int MorphByChar   = 3956;

        // ── Persistent state ─────────────────────────────────────────────────
        internal static int SourceSlideIndex { get; private set; } = -1;
        internal static readonly List<string> ZoomShapeNames = new List<string>();

        // ─────────────────────────────────────────────────────────────────────
        // 1. SELECT ZOOM
        //    Reads the current selection, renames shapes with a ZOOM_ prefix
        //    (PowerPoint Morph tracks shapes by name across slides), and stores
        //    the shape names together with the source slide index.
        // ─────────────────────────────────────────────────────────────────────
        internal static bool SelectZoom(PowerPoint.Application app)
        {
            if (app?.ActivePresentation == null)
            {
                Warn("Please open a presentation first.", "No Presentation");
                return false;
            }

            var win = app.ActiveWindow;
            if (win.Selection == null ||
                win.Selection.Type != PowerPoint.PpSelectionType.ppSelectionShapes)
            {
                Warn(
                    "No zoom areas found.\n\n" +
                    "Use 'Select Object' to add one or more rectangular zoom areas, " +
                    "then click 'Select Area'.",
                    "No Zoom Areas");
                return false;
            }

            var sr = win.Selection.ShapeRange;
            if (sr.Count < 1) { Warn("No shapes selected.", "No Shapes"); return false; }

            var srcSlide = win.View.Slide as PowerPoint.Slide;
            if (srcSlide == null)
            {
                Warn("Could not detect active slide.", "Zoom");
                return false;
            }

            var selectedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            for (int i = 1; i <= sr.Count; i++)
            {
                var sh = sr[i];

                if (!sh.Name.StartsWith("ZOOM_", StringComparison.OrdinalIgnoreCase))
                    sh.Name = "ZOOM_" + i + "_" + sh.Name;

                selectedNames.Add(sh.Name);
            }

            // If the slide contains generated zoom marker rectangles, always use
            // all of them. This supports copy/paste workflow where user creates
            // multiple zoom boxes but may not multi-select all before clicking.
            var markerNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            for (int i = 1; i <= srcSlide.Shapes.Count; i++)
            {
                try
                {
                    var sh = srcSlide.Shapes[i];
                    if (!IsZoomAreaMarkerShape(sh)) continue;

                    if (!sh.Name.StartsWith("ZOOM_", StringComparison.OrdinalIgnoreCase))
                        sh.Name = "ZOOM_AUTO_" + i + "_" + sh.Name;

                    markerNames.Add(sh.Name);
                }
                catch { }
            }

            if (markerNames.Count > 0)
            {
                selectedNames.Clear();
                foreach (var markerName in markerNames)
                    selectedNames.Add(markerName);
            }

            int selectedSlideIndex = win.View.Slide.SlideIndex;
            SourceSlideIndex = selectedSlideIndex;

            ZoomShapeNames.Clear();
            foreach (var name in selectedNames)
                ZoomShapeNames.Add(name);

            MessageBox.Show(
                $"{ZoomShapeNames.Count} zoom area(s) selected for Slide {SourceSlideIndex}.\n\n" +
                "Click 'Add + Create Zoom' to build the full morph sequence.",
                "Zoom Areas Selected",
                MessageBoxButtons.OK,
                MessageBoxIcon.Information);

            return true;
        }

        internal static bool AddZoomSelectionRectangle(PowerPoint.Application app)
        {
            if (!TryCreateZoomSelectionRectangle(app))
            {
                Warn("Could not add zoom area rectangle on the active slide.", "Zoom Area");
                return false;
            }

            return true;
        }

        private static bool TryCreateZoomSelectionRectangle(PowerPoint.Application app)
        {
            try
            {
                if (app?.ActivePresentation == null) return false;

                var win = app.ActiveWindow;
                if (win?.View == null) return false;

                var slide = win.View.Slide as PowerPoint.Slide;
                if (slide == null) return false;

                float slideW = app.ActivePresentation.PageSetup.SlideWidth;
                float slideH = app.ActivePresentation.PageSetup.SlideHeight;

                float w = slideW * 0.30f;
                float h = slideH * 0.30f;
                float left = (slideW - w) / 2f;
                float top = (slideH - h) / 2f;

                var rect = slide.Shapes.AddShape(
                    Office.MsoAutoShapeType.msoShapeRectangle,
                    left, top, w, h);

                rect.Name = "ZOOM_AREA_" + DateTime.Now.Ticks.ToString(CultureInfo.InvariantCulture);
                rect.Tags.Add(ZoomAreaMarkerTag, "True");
                rect.Fill.Visible = Office.MsoTriState.msoTrue;
                rect.Fill.Transparency = 1f;
                rect.Line.Visible = Office.MsoTriState.msoTrue;
                rect.Line.ForeColor.RGB = System.Drawing.ColorTranslator.ToOle(System.Drawing.Color.RoyalBlue);
                rect.Line.Weight = 2f;
                rect.Select();

                return true;
            }
            catch
            {
                return false;
            }
        }

        private static bool IsZoomAreaMarkerShape(PowerPoint.Shape sh)
        {
            try
            {
                if (sh == null) return false;
                if (sh.Tags[ZoomAreaMarkerTag] == "True") return true;

                string name = sh.Name ?? string.Empty;
                return name.StartsWith("ZOOM_AREA_", StringComparison.OrdinalIgnoreCase)
                    || name.StartsWith("ZOOM_AUTO_", StringComparison.OrdinalIgnoreCase);
            }
            catch
            {
                return false;
            }
        }

        // ─────────────────────────────────────────────────────────────────────
        // 2. ZOOM ADD
        //    For each stored zoom area, duplicates the source slide and scales
        //    every shape on the duplicate so that the zoom-area shape fills the
        //    entire slide (aspect ratio preserved, centred).
        //    Slides are inserted in reverse order so the forward sequence is
        //    area-1 first, area-N last.
        // ─────────────────────────────────────────────────────────────────────
        internal static void ZoomAdd(PowerPoint.Application app)
        {
            if (!ValidateState(app)) return;
            if (!EnsureMorphSupported(app)) return;

            var pres = app.ActivePresentation;
            var src  = pres.Slides[SourceSlideIndex];
            int sourceSlideId = src.SlideID;
            float slideW = pres.PageSetup.SlideWidth;
            float slideH = pres.PageSetup.SlideHeight;

            // Remove only slides previously generated for this source slide.
            RemoveTaggedSlidesForSource(pres, sourceSlideId);

            // Insert in REVERSE so the final order matches the stored list order.
            // Each Duplicate() always inserts at src.SlideIndex + 1; processing
            // last-to-first means earlier areas end up closer to the source.
            for (int z = ZoomShapeNames.Count - 1; z >= 0; z--)
            {
                var zArea = FindShape(src, ZoomShapeNames[z]);
                if (zArea == null) continue;

                src.Duplicate();                                      // inserts at src.SlideIndex + 1
                var preview = pres.Slides[src.SlideIndex + 1];
                preview.Tags.Add(ZoomTag, "true");
                preview.Tags.Add(ZoomSourceSlideIdTag, sourceSlideId.ToString(CultureInfo.InvariantCulture));
                TransformAllShapes(preview, zArea, slideW, slideH);
                ApplyMorph(preview);
            }

            MessageBox.Show(
                $"{ZoomShapeNames.Count} zoom preview slide(s) inserted after Slide {SourceSlideIndex}.\n\n" +
                "Click 'Create' to build the full Original → Zoom → Original sequence.",
                "Zoom Add",
                MessageBoxButtons.OK,
                MessageBoxIcon.Information);
        }

        // ─────────────────────────────────────────────────────────────────────
        // 3. CREATE
        //    Builds the complete morph-zoom sequence after the source slide:
        //
        //      Source(S)  →  ZoomIn₁  →  Return₁  →  ZoomIn₂  →  Return₂  …
        //
        //    Every inserted slide is tagged so it can be regenerated cleanly.
        //    Morph transition is applied to the source slide and all inserts.
        // ─────────────────────────────────────────────────────────────────────
        internal static void Create(PowerPoint.Application app)
        {
            if (!ValidateState(app)) return;
            if (!EnsureMorphSupported(app)) return;

            var pres = app.ActivePresentation;

            var src  = pres.Slides[SourceSlideIndex];
            int sourceSlideId = src.SlideID;
            RemoveTaggedSlidesForSource(pres, sourceSlideId); // clean only this source slide's generated slides
            float slideW = pres.PageSetup.SlideWidth;
            float slideH = pres.PageSetup.SlideHeight;

            // Give the source slide a Morph transition so the very first
            // zoom-in is animated when advancing from the slide before it.
            ApplyMorph(src);

            // Insert pairs in REVERSE order (last area processed first).
            //
            // For each area we insert two slides immediately after src:
            //   a) the zoom-in slide (duplicate with transform)
            //   b) the return-to-original slide (plain duplicate)
            //
            // Because every Duplicate() lands at src.SlideIndex + 1, inserting
            // in reverse means the first area ends up directly after src in the
            // finished deck.
            for (int z = ZoomShapeNames.Count - 1; z >= 0; z--)
            {
                var zArea = FindShape(src, ZoomShapeNames[z]);
                if (zArea == null) continue;

                // ── Return-to-original slide ─────────────────────────────────
                // (inserted first in the reversed loop, so it ends up AFTER the
                //  zoom-in slide in the final deck)
                src.Duplicate();
                var returnSlide = pres.Slides[src.SlideIndex + 1];
                returnSlide.Tags.Add(ZoomTag, "true");
                returnSlide.Tags.Add(ZoomSourceSlideIdTag, sourceSlideId.ToString(CultureInfo.InvariantCulture));
                ApplyMorph(returnSlide);

                // ── Zoom-in slide ────────────────────────────────────────────
                // (inserted second in the reversed loop, so it ends up BEFORE
                //  the return slide in the final deck)
                src.Duplicate();
                var zoomIn = pres.Slides[src.SlideIndex + 1];
                zoomIn.Tags.Add(ZoomTag, "true");
                zoomIn.Tags.Add(ZoomSourceSlideIdTag, sourceSlideId.ToString(CultureInfo.InvariantCulture));
                TransformAllShapes(zoomIn, zArea, slideW, slideH);
                ApplyMorph(zoomIn);
            }

            int inserted = ZoomShapeNames.Count * 2;
            MessageBox.Show(
                $"Zoom sequence created!\n\n" +
                $"{inserted} slides inserted after Slide {SourceSlideIndex}.\n" +
                $"Pattern: Original \u2192 Zoom \u2192 Original  (\u00d7{ZoomShapeNames.Count})\n\n" +
                "Morph transition applied to all slides.",
                "Success",
                MessageBoxButtons.OK,
                MessageBoxIcon.Information);
        }

        // ─────────────────────────────────────────────────────────────────────
        // Private helpers
        // ─────────────────────────────────────────────────────────────────────

        private static bool ValidateState(PowerPoint.Application app)
        {
            if (app?.ActivePresentation == null)
            {
                Warn("Please open a presentation first.", "No Presentation");
                return false;
            }
            if (SourceSlideIndex < 1 || ZoomShapeNames.Count == 0)
            {
                Warn(
                    "No zoom areas stored.\n\n" +
                    "Click 'Select Zoom Areas', select shapes on a slide, then try again.",
                    "No Zoom Areas");
                return false;
            }
            if (SourceSlideIndex > app.ActivePresentation.Slides.Count)
            {
                Warn("The source slide no longer exists in the presentation.", "Source Slide Missing");
                return false;
            }
            return true;
        }

        private static PowerPoint.Shape FindShape(PowerPoint.Slide slide, string name)
        {
            for (int i = 1; i <= slide.Shapes.Count; i++)
                if (string.Equals(slide.Shapes[i].Name, name, StringComparison.OrdinalIgnoreCase))
                    return slide.Shapes[i];
            return null;
        }

        /// <summary>
        /// Scales and translates every shape on <paramref name="slide"/> so that
        /// <paramref name="zArea"/> (whose geometry is read from the source slide)
        /// maps to the slide centre at full-slide size.  The uniform scale factor
        /// preserves each shape's aspect ratio.
        /// </summary>
        private static void TransformAllShapes(
            PowerPoint.Slide slide,
            PowerPoint.Shape zArea,
            float slideW,
            float slideH)
        {
            // Centre of the zoom-area on the source slide
            float zCX = zArea.Left + zArea.Width  / 2f;
            float zCY = zArea.Top  + zArea.Height / 2f;

            // Uniform scale that makes the zoom-area fill the slide
            // while preserving the original aspect ratio
            float scale = Math.Min(slideW / zArea.Width, slideH / zArea.Height);

            // Destination centre (middle of the slide)
            float dstCX = slideW / 2f;
            float dstCY = slideH / 2f;

            for (int i = 1; i <= slide.Shapes.Count; i++)
            {
                try
                {
                    var sh = slide.Shapes[i];

                    // Current centre of this shape
                    float cx = sh.Left + sh.Width  / 2f;
                    float cy = sh.Top  + sh.Height / 2f;

                    // New dimensions (uniform scale)
                    float nw = sh.Width  * scale;
                    float nh = sh.Height * scale;

                    // New centre: translate relative to zoom-area centre, then scale
                    float ncx = (cx - zCX) * scale + dstCX;
                    float ncy = (cy - zCY) * scale + dstCY;

                    sh.Width  = nw;
                    sh.Height = nh;
                    sh.Left   = ncx - nw / 2f;
                    sh.Top    = ncy - nh / 2f;
                }
                catch
                {
                    // Skip shapes that cannot be repositioned (e.g. locked placeholders)
                }
            }
        }

        /// <summary>
        /// Applies the Morph (ppEffectMorphByObject = 3954) transition to <paramref name="slide"/>.
        /// Clears any existing transition first, then sets the correct Morph value via
        /// a direct enum cast so PowerPoint stores it as Morph, not Fade.
        /// </summary>
        private static void ApplyMorph(PowerPoint.Slide slide)
        {
            var t = slide.SlideShowTransition;

            // Clear any previously applied transition before setting Morph
            t.EntryEffect = PowerPoint.PpEntryEffect.ppEffectNone;

            // Set Morph by Object (3954 is the correct value for Microsoft 365 / PP 2016+)
            t.EntryEffect    = (PowerPoint.PpEntryEffect)MorphByObject;
            t.Duration       = 0.7f;
            t.AdvanceOnClick = Office.MsoTriState.msoTrue;
            t.AdvanceOnTime  = Office.MsoTriState.msoFalse;
        }

        /// <summary>
        /// Returns true if the running PowerPoint is version 16.0 or later (2016 / Office 365).
        /// Shows a blocking error and returns false otherwise so the caller can exit early.
        /// </summary>
        private static bool EnsureMorphSupported(PowerPoint.Application app)
        {
            try
            {
                float ver = float.Parse(app.Version, CultureInfo.InvariantCulture);
                if (ver >= 16.0f) return true;

                MessageBox.Show(
                    $"Morph transition requires PowerPoint 2016 (version 16.0) or later.\n\n" +
                    $"Your installed version: {app.Version}\n\n" +
                    "Please upgrade to PowerPoint 2016 or Office 365 to use this feature.",
                    "Morph Not Supported",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
                return false;
            }
            catch
            {
                return true;   // version check failed — proceed optimistically
            }
        }

        /// <summary>
        /// Deletes slides generated from the same source slide by a previous ZoomAdd/Create call.
        /// Iterates backwards so index shifting does not skip slides.
        /// </summary>
        private static void RemoveTaggedSlidesForSource(PowerPoint.Presentation pres, int sourceSlideId)
        {
            string sourceIdText = sourceSlideId.ToString(CultureInfo.InvariantCulture);

            for (int i = pres.Slides.Count; i >= 1; i--)
            {
                try
                {
                    var s = pres.Slides[i];
                    if (s.Tags[ZoomTag] == "true" && s.Tags[ZoomSourceSlideIdTag] == sourceIdText)
                        pres.Slides[i].Delete();
                }
                catch { }
            }
        }

        private static void Warn(string msg, string title) =>
            MessageBox.Show(msg, title, MessageBoxButtons.OK, MessageBoxIcon.Warning);
    }
}
